# Generated by Django 5.2.14 on 2026-06-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_store_is_setup_complete_user_pin_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_cash',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_store_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='receipt_copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='store',
            name='receipt_footer',
            field=models.CharField(blank=True, default='Visit us again!', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='receipt_header',
            field=models.CharField(blank=True, default='Thank you for shopping with us!', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='receipt_paper_size',
            field=models.CharField(choices=[('80mm', '80mm'), ('58mm', '58mm'), ('a4', 'A4')], default='80mm', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='receipt_show_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='receipt_show_tax_breakdown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
