# Generated by Django 5.2.14 on 2026-06-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_store_city_store_payment_card_store_payment_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='appearance_accent_color',
            field=models.CharField(choices=[('indigo', 'Indigo'), ('blue', 'Blue'), ('violet', 'Violet'), ('emerald', 'Emerald'), ('rose', 'Rose'), ('amber', 'Amber'), ('slate', 'Slate')], default='indigo', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='appearance_compact_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='appearance_sidebar_collapsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='appearance_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='locale_date_format',
            field=models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='MM/DD/YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='locale_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='locale_number_format',
            field=models.CharField(choices=[('1,234.56', '1,234.56'), ('1.234,56', '1.234,56'), ('1 234.56', '1 234.56')], default='1,234.56', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='locale_time_format',
            field=models.CharField(choices=[('12h', '12 Hour'), ('24h', '24 Hour')], default='12h', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='locale_timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='low_stock_threshold_default',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='store',
            name='notification_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='notify_daily_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='notify_low_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='notify_new_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='notify_refund',
            field=models.BooleanField(default=True),
        ),
    ]
