# Generated by Django 5.2.14 on 2026-06-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_store_appearance_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='gst_business_name',
            field=models.CharField(blank=True, help_text='Legal business name as per GST registration', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='gst_composition_scheme',
            field=models.BooleanField(default=False, help_text='Whether registered under composition scheme'),
        ),
        migrations.AddField(
            model_name='store',
            name='gst_default_slab',
            field=models.CharField(choices=[('0', '0% - Exempt'), ('5', '5% GST'), ('12', '12% GST'), ('18', '18% GST'), ('28', '28% GST')], default='18', help_text='Default GST slab for new products', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='gst_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='gst_inclusive_pricing',
            field=models.BooleanField(default=False, help_text='Product prices include GST'),
        ),
        migrations.AddField(
            model_name='store',
            name='gst_state_code',
            field=models.CharField(blank=True, help_text='2-digit state code', max_length=2),
        ),
        migrations.AddField(
            model_name='store',
            name='gst_state_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='gstin',
            field=models.CharField(blank=True, help_text='15-character GSTIN number', max_length=15),
        ),
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Standard Rate, Reduced Rate', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate percentage', max_digits=5)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('hsn_code', models.CharField(blank=True, help_text='Associated HSN/SAC code', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_slabs', to='accounts.store')),
            ],
            options={
                'ordering': ['rate'],
            },
        ),
    ]
