# Generated by Django 5.2.14 on 2026-06-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_store_gst_business_name_store_gst_composition_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='demand_tracking_enabled',
            field=models.BooleanField(default=True, help_text='Enable customer demand tracking'),
        ),
    ]
