# Generated by Django 5.2.14 on 2026-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_store_demand_tracking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='notify_demand_fulfilled',
            field=models.BooleanField(default=True, help_text='Send email to customers when requested product arrives'),
        ),
    ]
