# Generated by Django 5.2.14 on 2026-06-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_store_notify_demand_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='refund_enabled',
            field=models.BooleanField(default=True, help_text='Allow refunds'),
        ),
        migrations.AddField(
            model_name='store',
            name='refund_require_reason',
            field=models.BooleanField(default=True, help_text='Require reason for refunds'),
        ),
        migrations.AddField(
            model_name='store',
            name='refund_time_limit_days',
            field=models.PositiveIntegerField(default=30, help_text='Days after sale within which refund is allowed, 0 for unlimited'),
        ),
    ]
