# Generated by Django 5.2.14 on 2026-06-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_store_refund_enabled_store_refund_require_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='printer_address',
            field=models.CharField(blank=True, help_text='IP:port for network, vendor:product for USB, /dev/path for serial', max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='printer_auto_print',
            field=models.BooleanField(default=False, help_text='Auto-print receipt after every sale'),
        ),
        migrations.AddField(
            model_name='store',
            name='printer_paper_width',
            field=models.PositiveIntegerField(default=48, help_text='Characters per line (32 for 58mm, 48 for 80mm)'),
        ),
        migrations.AddField(
            model_name='store',
            name='printer_type',
            field=models.CharField(choices=[('none', 'None'), ('test', 'Test (Dummy)'), ('usb', 'USB'), ('network', 'Network'), ('serial', 'Serial')], default='none', max_length=10),
        ),
    ]
