# Generated by Django 5.2.14 on 2026-06-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_store_printer_address_store_printer_auto_print_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='oneupi_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='oneupi_api_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI VPA e.g. store@upi', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='upi_payee_name',
            field=models.CharField(blank=True, help_text='Display name for UPI payments', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='upi_verification_mode',
            field=models.CharField(choices=[('manual', 'Manual Confirmation'), ('oneupi', 'OneUPI (Auto-verify)')], default='manual', max_length=10),
        ),
    ]
