# Generated by Django 5.2.14 on 2026-06-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_store_oneupi_api_key_store_oneupi_api_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current cash in drawer', max_digits=10),
        ),
    ]
