# Generated by Django 5.2.14 on 2026-06-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_terminal_cash_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='appearance_accent_color',
            field=models.CharField(default='indigo', max_length=20),
        ),
    ]
