# Generated by Django 5.2.14 on 2026-06-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_store_appearance_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='discount_enabled',
            field=models.BooleanField(default=True, help_text='Allow discounts on sales'),
        ),
        migrations.AddField(
            model_name='store',
            name='discount_max_percent_cashier',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Max discount % a cashier can give', max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='discount_max_percent_manager',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Max discount % a manager can give', max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='discount_require_approval',
            field=models.BooleanField(default=False, help_text='Cashier discounts need manager approval'),
        ),
        migrations.AddField(
            model_name='store',
            name='discount_require_reason',
            field=models.BooleanField(default=False, help_text='Require reason for discounts'),
        ),
    ]
