# Generated by Django 5.2.14 on 2026-06-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override GST rate for this product', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN/SAC code for GST', max_length=20),
        ),
    ]
