# Generated by Django 5.2.14 on 2026-06-03 10:06

import uuid
from django.db import migrations, models


def populate_receipt_numbers(apps, schema_editor):
    Sale = apps.get_model('sales', 'Sale')
    for sale in Sale.objects.filter(receipt_number=''):
        sale.receipt_number = f"RCP-{uuid.uuid4().hex[:8].upper()}"
        sale.save(update_fields=['receipt_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True),
        ),
        # Step 1: Add receipt_number without unique constraint
        migrations.AddField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, default=''),
        ),
        # Step 2: Populate existing rows with unique receipt numbers
        migrations.RunPython(populate_receipt_numbers, migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='sale',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
