# Generated by Django 5.2.14 on 2026-06-03 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_store_oneupi_api_key_store_oneupi_api_secret_and_more'),
        ('sales', '0004_refund_refunditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpiPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upi_id', models.CharField(max_length=100)),
                ('transaction_ref', models.CharField(max_length=50, unique=True)),
                ('upi_link', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('verification_mode', models.CharField(default='manual', max_length=10)),
                ('oneupi_order_id', models.CharField(blank=True, max_length=100)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upi_payment', to='sales.sale')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upi_payments', to='accounts.store')),
            ],
        ),
    ]
