# Generated by Django 5.2.14 on 2026-06-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_upipayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('flat', 'Flat Amount'), ('percent', 'Percentage')], default='flat', max_length=10),
        ),
    ]
