# Generated by Django 5.2.14 on 2026-06-03 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_store_demand_tracking_enabled'),
        ('products', '0002_product_gst_rate_product_hsn_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='What the customer asked for', max_length=255)),
                ('query_normalized', models.CharField(db_index=True, help_text='Lowercase trimmed version for grouping', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('fulfilled', 'Fulfilled'), ('dismissed', 'Dismissed')], default='new', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_logs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Linked product if it exists in catalog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_requests', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_requests', to='accounts.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
