# Generated by Django 5.2.14 on 2026-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandrequest',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Customer email for notification', max_length=254),
        ),
        migrations.AddField(
            model_name='demandrequest',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Customer name', max_length=255),
        ),
        migrations.AddField(
            model_name='demandrequest',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='demandrequest',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='When the customer was notified', null=True),
        ),
        migrations.AddField(
            model_name='demandrequest',
            name='notify_customer',
            field=models.BooleanField(default=False, help_text='Send email when product arrives'),
        ),
    ]
